### ISSUE TITLE
Abode broken [again] 

### ISSUE THREAD

**Issue by JoshuaGarrison27** [arsaboo/homeassistant-config#10]
I see that you are on version 0.69.0 but I am on 0.69.1 and I am getting this error in my logs. Are you getting anything similar? If so, I am just seeing what you might have done to fix it.

I attempted to unlock the door and it cannot find the service either. I just removed the custom_component that you orginially told me to do when the updates for 2FA came out a month or two ago. (Im not using 2FA).

```
2018-05-20 10:12:44 ERROR (MainThread) [homeassistant.setup] Error during setup of component abode
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 145, in _async_setup_component
    component.setup, hass, processed_config)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/abode.py", line 136, in setup
    username, password, cache, name, polling, exclude, lights)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/abode.py", line 97, in __init__
    get_automations=True, cache_path=cache)
TypeError: __init__() got an unexpected keyword argument 'cache_path'
2018-05-20 10:13:05 ERROR (Dummy-4) [homeassistant.core] Error doing job: Task was destroyed but it is pending!
2018-05-20 10:16:25 WARNING (MainThread) [homeassistant.core] Unable to find service lock/unlock
```

**Comment by arsaboo** [comment]
Abode is working perfectly for me here. Nothing in the logs for me. I don't have lights added to Abode and may be that is causing the error.

**Comment by JoshuaGarrison27** [comment]
Sorry forgot to come back to this. Found out it was user error on my part. It all works individually. I have a custom group for mine and it happens if I try to hit the group toggle. So nevermind. It works when individually called. Thanks.
